
export const Letters={
  russian:[],
  english:[
    {letter:"A",value:1},
    {letter:"B",value:3},
    {letter:"C",value:3},
    {letter:"D",value:2},
    {letter:"E",value:1},
    {letter:"F",value:4},
    {letter:"G",value:2},
    {letter:"H",value:4},
    {letter:"I",value:1},
    {letter:"J",value:8},
    {letter:"K",value:5},
    {letter:"L",value:1},
    {letter:"M",value:3},
    {letter:"N",value:1},
    {letter:"O",value:1},
    {letter:"P",value:3},
    {letter:"Q",value:10},
    {letter:"R",value:1},
    {letter:"S",value:1},
    {letter:"T",value:1},
    {letter:"U",value:1},
    {letter:"V",value:4},
    {letter:"W",value:4},
    {letter:"X",value:8},
    {letter:"Z",value:10}
  ]
}
export const Board = {
  0: { multiply: 3, object: "word" },
  3: { multiply: 2, object: "letter" },
  7: { multiply: 3, object: "word" },
  11: { multiply: 2, object: "letter" },
  14: { multiply: 3, object: "word" },
  16: { multiply: 2, object: "word" },
  20: { multiply: 3, object: "letter" },
  24: { multiply: 3, object: "letter" },
  28: { multiply: 2, object: "word" },
  32: { multiply: 2, object: "word" },
  36: { multiply: 2, object: "letter" },
  38: { multiply: 2, object: "letter" },
  42: { multiply: 2, object: "word" },
  45: { multiply: 2, object: "letter" },
  48: { multiply: 2, object: "word" },
  52: { multiply: 2, object: "letter" },
  56: { multiply: 2, object: "word" },
  59: { multiply: 2, object: "letter" },
  64: { multiply: 2, object: "word" },
  70: { multiply: 2, object: "word" },
  76: { multiply: 3, object: "letter" },
  80: { multiply: 3, object: "letter" },
  84: { multiply: 3, object: "letter" },
  88: { multiply: 3, object: "letter" },
  92: { multiply: 2, object: "letter" },
  96: { multiply: 2, object: "letter" },
  98: { multiply: 2, object: "letter" },
  102: { multiply: 2, object: "letter" },
  105: { multiply: 3, object: "word" },
  108: { multiply: 2, object: "letter" },
  112: { object: "star" },
  116: { multiply: 2, object: "letter" },
  119: { multiply: 3, object: "word" },
  122: { multiply: 2, object: "letter" },
  126: { multiply: 2, object: "letter" },
  128: { multiply: 2, object: "letter" },
  132: { multiply: 2, object: "letter" },
  136: { multiply: 3, object: "letter" },
  140: { multiply: 3, object: "letter" },
  144: { multiply: 3, object: "letter" },
  148: { multiply: 3, object: "letter" },
  154: { multiply: 2, object: "word" },
  160: { multiply: 2, object: "word" },
  165: { multiply: 2, object: "letter" },
  168: { multiply: 2, object: "word" },
  172: { multiply: 2, object: "letter" },
  176: { multiply: 2, object: "word" },
  179: { multiply: 2, object: "letter" },
  182: { multiply: 2, object: "word" },
  186: { multiply: 2, object: "letter" },
  188: { multiply: 2, object: "letter" },
  192: { multiply: 2, object: "word" },
  196: { multiply: 2, object: "word" },
  200: { multiply: 3, object: "letter" },
  204: { multiply: 3, object: "letter" },
  208: { multiply: 2, object: "word" },
  210: { multiply: 3, object: "word" },
  213: { multiply: 2, object: "letter" },
  217: { multiply: 3, object: "word" },
  221: { multiply: 2, object: "letter" },
  224: { multiply: 3, object: "word" },
};